version: '3.9'

services:
  dom-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: dom-db:1.0.0
    container_name: dom-db
    restart: always
    ports:
      - 5555:5432
    volumes:
      - dom-db:/var/lib/postgresql/data

volumes:
  dom-db:
